apiVersion: v1
data:
  REDIS_OUTPUT_KEY: jt304-proj3-output
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-06T02:48:31Z"
  name: outputkey
  namespace: jt304
  resourceVersion: "4457471"
  uid: 4b5e3e15-9db6-4fda-90dc-c32f3d2a887d
